### ISSUE TITLE
Broken dependencies on Centos8 

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/python-pysteps-rpm#1]
```
[root@otto ~]# dnf install --refresh python3-pysteps                                 
 Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides python3-opencv needed by python3-pysteps-1.3.2-1.simc.20200901.gitb5aa2fe.x86_64
  - nothing provides python3.6dist(jsmin) needed by python3-pysteps-1.3.2-1.simc.20200901.gitb5aa2fe.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by brancomat** [comment]
Aggiornamenti vari

Aperta issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1910728

Nel pacchetto sorgente dell'ultimo opencv (3.4.6) su centos8 c'è uno spec che sembra prevedere il pacchetto `python3-opencv` ma non è stato possibile testare il build perché sembrano mancare le seguenti dipendenze:
`ceres-solver-devel, SFML-devel, libdc1394-devel`
(da approfondire perché potrebbe bastare abilitare qualche modulo/repository esotico di centos)

Volendo c'è un repo third party che sembra ospitare una versione di opencv con i binding:
https://centos.pkgs.org/8/okey-x86_64/python3-opencv-3.4.1-9.el8.x86_64.rpm.html

**Comment by brancomat** [comment]
La issue su redhat è stata chiusa, dice di chiedere a centos, ho chiesto a centos
https://bugs.centos.org/view.php?id=18156

**Comment by edigiacomo** [comment]
bugs.centos.org è stato chiuso l'anno scorso (https://pagure.io/centos-infra/issue/1152), comunque ho testato su Rocky 8 (`monci run rocky8 dnf install -y python3-pysteps`) e si installa correttamente. Chiudo.
